# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8154209e8788f441ac0eee0692053c2a95103415aa08a77755a44609f1f02305131f75575113234e70f75f4edf3f87613f8046f166f88bed6160c98a4e67f522

test:
  secret_key_base: 80de45facc6d23601c30b97223959c986b98162ef6f84ee294dc23f7ee7715c9917727f76d0a733f1c31a119e32b7804bdf2fe692a6bc1d6767ac9d6fb8ee223

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
